# Generated by Django 5.0.6 on 2025-10-05 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='news_catego_nombre_849dcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('autor_id', models.UUIDField()),
                ('autor_institucion_id', models.UUIDField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('tipo_autor', models.CharField(choices=[('usuario', 'Usuario'), ('institucion', 'Institución')], max_length=20)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='news.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='news.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='news.comentario')),
                ('comentario_respuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_a', to='news.comentario')),
            ],
            options={
                'indexes': [models.Index(fields=['comentario_padre'], name='idx_resp_padre')],
            },
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['autor_id'], name='idx_publicaciones_autor'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['autor_institucion_id'], name='idx_publicaciones_institucion'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['categoria'], name='idx_publicaciones_categoria'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['estado'], name='idx_publicaciones_estado'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['publicacion'], name='idx_likes_publicacion'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['usuario_id'], name='idx_likes_usuario'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('publicacion', 'usuario_id'), name='uniq_like_pub_usuario'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['publicacion'], name='idx_comentarios_publicacion'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['usuario_id'], name='idx_comentarios_usuario'),
        ),
    ]
